### PR TITLE
feat(portal):sync ldap data to redis queue

### PR DESCRIPTION
**Pull request by liguoab**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @pendoragon  @ijumps 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pendoragon** [comment]
这个应该已经在用了吧？

**Comment by liguoab** [comment]
嗯 提交的这几个 pr 都上线在用了

**Pull request merged**
